version: '2.1'

services:
  website:
    build: domain-services/website-service
    mem_limit: 200m
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      mysql:
        condition: service_healthy

  result:
    build: domain-services/result-service
    mem_limit: 350m
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      mongodb:
        condition: service_healthy

  scraper:
    build: domain-services/scraper-service
    mem_limit: 500m
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      mysql:
        condition: service_healthy

  search:
    build: domain-services/search-service
    mem_limit: 200m
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      mysql:
        condition: service_healthy

  mongodb:
    image: mongo:4.4.2
    mem_limit: 512m
    ports:
      - "27017:27017"
    command: mongod
    healthcheck:
      test: "mongo --eval 'db.stats().ok'"
      interval: 5s
      timeout: 2s
      retries: 60

  mysql:
    image: mysql:5.7.32
    mem_limit: 512m
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=9088007
      - MYSQL_DATABASE=website-db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=9088007
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=9088007 --execute \"SHOW DATABASES;\""
      interval: 5s
      timeout: 2s
      retries: 60