springdoc:
  swagger-ui.path: /openapi/swagger-ui.html
  api-docs.path: /openapi/v3/api-docs
  packagesToScan: com.barak.domain-services.search-service
  pathsToMatch: /**

# Strongly recommended setting this property to "none" in a production environment!
spring.jpa.hibernate.ddl-auto: update

spring.datasource.hikari.initializationFailTimeout: 15000

spring.datasource:
  url: jdbc:mysql://localhost:3306/website-db
  username: root
  password: 9088007

server.port: 7001
server.error.include-message: always

logging:
  level:
    root: INFO
    com.barak: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptior.sql.BasicBinder: TRACE

---

spring:
  config:
    activate:
      on-profile: docker

server:
  port: 8080

spring.datasource:
  url: jdbc:mysql://localhost:3306/website-db


